meta_product_name: "Hurryup"
meta_title: "Hurryup - Better serv ever"
meta_description: "With Hurryup no need to run after the waiter anymore"
meta_image: "Hurryup_image.png" # should exist in `app/assets/images/`
twitter_account: "@hurryup_product_twitter_account"   # required for Twitter Cards
